version: "3.9"

services:
    web:
      image: nginx:latest
      container_name: comunna-searcher-web
      ports:
        - 8007:80
      volumes:
        - ./:/var/www/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - comunna-network
      links:
        - php

    php:
        build: ./
        container_name: comunna-searcher-php
        networks:
          - comunna-network
        volumes:
          - ./:/var/www/html

networks:
    comunna-network:
        external:
            name: develop-network